
modLoader="javafml"
loaderVersion="[1,)"
license="MIT"


[[mods]]
modId="formicapi"
version = "1.21.1_1.3"
displayName="Formic API"
logoFile = "logo.png"
credits='''
Source code:
RealAntEngineer
'''
authors="Real Ant Engineer"

description='''
Core mod and API used in mods of the Engineer Colony team
'''

[[dependencies.formicapi]]
modId="create"
mandatory=true
versionRange="[0.6.0.1,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "formicapi.mixins.json"