
modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"


[[mods]]
modId="${mod_id}"
version = "${mod_version}"
displayName="${mod_name}"
logoFile = "logo.png"
credits='''
Source code:
RealAntEngineer
'''
authors="Real Ant Engineer"

description='''
Core mod and API used in mods of the Engineer Colony team
'''

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="[0.6.0.1,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "formicapi.mixins.json"